Repository cloudfoundry/docs-running-cf, pull requests merged in 2018-10, with the labels that each got.

#63 Update Volume Services Page
  deploy-vol-services.html.md.erb
Labels: in progress

#65 Add SMB section to the Adding Volume Services guide
  deploy-vol-services.html.md.erb
Labels: delivered

#64 Update deploy-vol-services.html.md.erb to remove reference to 'nfs-experimental'
  deploy-vol-services.html.md.erb
Labels: scheduled
